export const SOURCES = [
  {
    id: 'mmguo-home',
    name: '秒秒Guo',
    platform: 'personal-site',
    kind: 'html-list',
    group: 'creator',
    url: 'https://mmguo.dev',
    homepage: 'https://mmguo.dev',
  },
  {
    id: 'bilibili-chimp',
    name: '第四种黑猩猩CHIMP',
    platform: 'bilibili',
    kind: 'rsshub',
    group: 'creator',
    path: '/bilibili/user/video/3546830396721763',
    homepage: 'https://space.bilibili.com/3546830396721763',
    timeoutMs: 90_000,
    configHint: 'B站匿名访问被风控时，需要在 .env 配置 BILIBILI_COOKIE_1 后重启 RSSHub。',
  },
  {
    id: 'bilibili-donquixote',
    name: '唐吉可德拉曼查的英豪',
    platform: 'bilibili',
    kind: 'rsshub',
    group: 'creator',
    path: '/bilibili/user/video/341376543',
    homepage: 'https://space.bilibili.com/341376543',
    timeoutMs: 90_000,
    configHint: 'B站匿名访问被风控时，需要在 .env 配置 BILIBILI_COOKIE_1 后重启 RSSHub。',
  },
  {
    id: 'wechat-khazix',
    name: '数字生命卡兹克',
    platform: 'wechat',
    kind: 'rsshub',
    group: 'creator',
    urlEnv: 'WECHAT_KHAZIX_RSS_URL',
    path: '/wechat/sogou/Rockhazix',
    fallbackPaths: ['/wechat/uread/Rockhazix'],
    homepage: 'https://weixin.sogou.com/weixin?type=1&query=Rockhazix',
    timeoutMs: 90_000,
    minIntervalHours: 2,
    configHint:
      '微信公众号通过 RSSHub 间接源抓取，当前优先尝试搜狗微信，失败后尝试 uread；更稳的长期方案是自托管 we-mp-rss 后把 feed 接入。',
  },
  {
    id: 'aihot-khazix',
    name: '卡兹克（AI HOT兜底）',
    platform: 'aihot',
    kind: 'aihot',
    group: 'creator',
    url: 'https://aihot.virxact.com/api/public/items',
    homepage: 'https://aihot.virxact.com',
    mode: 'all',
    pageSize: 100,
    maxPages: 20,
    recentWindowHours: 24,
    sourceIncludes: ['卡兹克', '数字生命', 'Khazix'],
    configHint: 'AI HOT 兜底源按 source 字段过滤卡兹克相关条目；不依赖关键词搜索。',
  },
  {
    id: 'claude-blog',
    name: 'Claude Blog',
    platform: 'official-blog',
    kind: 'claude-blog',
    group: 'official',
    url: 'https://claude.com/blog',
    homepage: 'https://claude.com/blog',
  },
  {
    id: 'openai-news',
    name: 'OpenAI News',
    platform: 'official-blog',
    kind: 'rss',
    group: 'official',
    url: 'https://openai.com/news/rss.xml',
    homepage: 'https://openai.com/news/',
  },
  {
    id: 'langchain-blog',
    name: 'LangChain Blog',
    platform: 'official-blog',
    kind: 'rss',
    group: 'official',
    url: 'https://www.langchain.com/blog/rss.xml',
    homepage: 'https://www.langchain.com/blog',
  },
  {
    id: 'aihot',
    name: 'AI HOT',
    platform: 'aihot',
    kind: 'aihot',
    group: 'aihot',
    url: 'https://aihot.virxact.com/api/public/items',
    homepage: 'https://aihot.virxact.com',
    keywords: ['Codex', 'Claude Code', 'agent', 'skills', '知识库', 'MCP', 'OpenAI', 'Anthropic'],
  },
];
